key = "PseudoElementsType"
value = ["typing = \"Unit\"\nident = \"None\"\nfield = []\n", "typing = \"Unit\"\nident = \"Invalid\"\nfield = []\n", "typing = \"Unit\"\nident = \"Before\"\nfield = []\n", "typing = \"Unit\"\nident = \"After\"\nfield = []\n", "typing = \"Unit\"\nident = \"Selection\"\nfield = []\n"]
